version: '3.8'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: taskiDB
    container_name: taskiDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
